[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
example_addr = "_"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
