[package]
name = "airdropper"
version = "0.0.1"
# upgrade_policy = "compatible"

[addresses]
my_addr = "0x4139eaf9a8f1ee32431e6d33876a8a4243be4b0d7fbf76f0cb0315ec92452369"
std = "0x1"
aptos_framework = "0x1"
aptos_token="0x3"

[dependencies]
MoveStdlib = { local = "../../../aptos-core/aptos-move/framework/move-stdlib/" }
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token/" }
# MoveStdlib = { local = "/Users/liaohua/aptos-core/aptos-move/framework/move-stdlib" }
# AptosFramework = { local = "/Users/liaohua/aptos-core/aptos-move/framework/aptos-framework" }
